version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: easyaccess
      POSTGRES_USER: easyaccess
      POSTGRES_PASSWORD: easyaccess
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./easyaccess-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/easyaccess
      SPRING_DATASOURCE_USERNAME: easyaccess
      SPRING_DATASOURCE_PASSWORD: easyaccess
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./easyaccess-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: